import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import { createClient } from "@supabase/supabase-js";
import { runScenario, compareStep, type TargetHandle } from "@supadiff/engine";
import {
  parseScenarioSpec,
  parseTargetSpec,
  computeScenarioDigest,
  sha256OfCanonicalJson,
  type ComparisonPolicy,
  type ScenarioSpec,
} from "@supadiff/spec";
import {
  createSupaliteDriver,
  createSupabaseLocalDriver,
  scaffoldSupabaseLocalProject,
  forceCleanupProject,
  startStack,
  SupabaseLocalTargetSession,
  type SupabaseLocalTargetConfig,
} from "../../src/index.js";
import { spawnManaged } from "../../src/shared/process.js";

const REPO_ROOT = path.resolve(fileURLToPath(new URL("../../../../", import.meta.url)));

function loadScenario(name: string): ScenarioSpec {
  return parseScenarioSpec(
    JSON.parse(readFileSync(path.join(REPO_ROOT, "scenarios", "deterministic", name), "utf8")),
  );
}

const LOCAL_CONFIG: SupabaseLocalTargetConfig = {
  dbMajorVersion: 17,
  excludedServices: [],
  experimentalFeatures: ["storage"],
  keyMode: "opaque-v1",
  routePrefixes: { auth: "/auth/v1", rest: "/rest/v1", storage: "/storage/v1" },
  analytics: false,
  readinessTimeoutMs: 120_000,
};

function supaliteSpec(id: string) {
  return parseTargetSpec({
    id,
    kind: "supalite-sqlite-postgres",
    package: { name: "@supabase/lite", version: "0.9.0" },
    runtime: { runtime: "node", version: process.version },
    backend: { backend: "sqlite-postgres" },
    config: {
      admin: false,
      forceRollback: false,
      experimentalFeatures: [],
      keyMode: "opaque-v1",
      routePrefixes: { auth: "/auth/v1", rest: "/rest/v1", storage: "/storage/v1" },
      transport: "socket-server",
      readinessTimeoutMs: 30000,
    },
    credentialRefs: [],
    lifecycle: {
      allocation: "provision-new",
      isolation: "fresh-instance",
      readinessTimeoutMs: 30000,
      teardownTimeoutMs: 10000,
      cleanup: "always",
      keepOnFailure: "deny",
    },
    safety: {
      allowHosted: false,
      allowHostedCreate: false,
      allowHostedDestructive: false,
      maxHostedCostUsd: 0,
    },
  });
}

function supabaseLocalSpec(id: string, overrides: Record<string, unknown> = {}) {
  return parseTargetSpec({
    id,
    kind: "supabase-local",
    package: { name: "supabase", version: "2.116.0" },
    runtime: { runtime: "node", version: process.version },
    backend: { backend: "postgres", version: "17" },
    config: { ...LOCAL_CONFIG },
    credentialRefs: [],
    lifecycle: {
      allocation: "provision-new",
      isolation: "fresh-instance",
      readinessTimeoutMs: 120000,
      teardownTimeoutMs: 60000,
      cleanup: "always",
      keepOnFailure: "deny",
    },
    safety: {
      allowHosted: false,
      allowHostedCreate: false,
      allowHostedDestructive: false,
      maxHostedCostUsd: 0,
    },
    ...overrides,
  });
}

const IGNORE = (reason: string): ComparisonPolicy["rules"][number]["rule"] => ({
  kind: "explicit-ignore",
  reason,
  evidence: [{ kind: "note", value: "Architecture Contract §9.3 (target-local value)" }],
});
const EXACT = { kind: "exact" as const };

const SERVICE_OF: Record<string, string> = {
  "auth.signUp": "auth",
  "observe.authSession": "auth",
  "data.insert": "data",
  "data.select": "data",
  "observe.dataReadback": "data",
};

function rule(
  operationId: string,
  observablePath: string,
  r: ComparisonPolicy["rules"][number]["rule"],
  rationale: string,
): ComparisonPolicy["rules"][number] {
  return {
    id: `rule.l7-${operationId.replace(/\./g, "-")}-${observablePath.replace(/\W+/g, "-")}`.toLowerCase(),
    version: "1",
    selector: {
      service: SERVICE_OF[operationId]!,
      operationId,
      operationVersion: "1",
      observablePath,
      referenceTargetSelector: { kind: "supalite-sqlite-postgres" },
      candidateTargetSelector: { kind: "supabase-local" },
    },
    inputType: "any",
    rule: r,
    strictness: "contract",
    rationale,
    evidence: [],
  };
}

/**
 * The row shape `public.todos` returns: `title` is scenario-authored and must match
 * across targets; `id`/`owner_id`/`created_at` are each independently generated by the
 * target (a UUID from that target's own `gen_random_uuid()` / GoTrue, a wall-clock
 * timestamp) and are excluded the same way §9.3 excludes nonces and wall time from a
 * divergence signature.
 */
const ROW_ITEM: ComparisonPolicy["rules"][number]["rule"] = {
  kind: "object",
  unknown: "fail",
  fields: [
    { field: "/title", rule: EXACT },
    { field: "/id", rule: IGNORE("row id is a target-local UUID") },
    { field: "/owner_id", rule: IGNORE("owner_id is the target-local signup UUID") },
    { field: "/created_at", rule: IGNORE("created_at is target-local wall time") },
  ],
};

const L7_POLICY: ComparisonPolicy = {
  format: "supadiff.comparison-policy",
  formatVersion: "1.0",
  policyId: "policy.peer-data-auth-rls-smoke",
  policyVersion: "1",
  rules: [
    rule("auth.signUp", "/status", EXACT, "signup must succeed identically"),
    rule("auth.signUp", "/user/email", EXACT, "signup echoes the scenario-authored email"),
    rule("auth.signUp", "/user/id", IGNORE("user id is a target-local UUID"), "not portable"),
    rule("observe.authSession", "/active", EXACT, "the post-signup session is active on both"),
    rule("observe.authSession", "/role", EXACT, "the authenticated role is reported identically"),
    rule("observe.authSession", "/subject", IGNORE("subject is the target-local user UUID"), "np"),
    rule("data.insert", "/status", EXACT, "owner-authorized insert must succeed identically"),
    rule(
      "data.insert",
      "/rows",
      { kind: "unordered-collection", key: "/title", item: ROW_ITEM },
      "RLS-authorized insert returns the owned row on both",
    ),
    rule("observe.dataReadback", "/status", EXACT, "post-insert readback status"),
    rule(
      "observe.dataReadback",
      "/rows",
      { kind: "unordered-collection", key: "/title", item: ROW_ITEM },
      "owner readback sees exactly the owned row on both",
    ),
    rule("data.select", "/status", EXACT, "select status must match"),
    rule(
      "data.select",
      "/rows",
      { kind: "unordered-collection", key: "/title", item: ROW_ITEM },
      "owner sees the row; anon sees none — the RLS behavior compared for real",
    ),
  ],
};

const COMPARED_STEPS = [
  "step.signup",
  "step.session-read",
  "step.insert",
  "step.readback",
  "step.select-owner",
  "step.select-anon",
];

const projects: string[] = [];
afterEach(async () => {
  for (const id of projects.splice(0)) await forceCleanupProject(id).catch(() => undefined);
});

describe("L7 peer: Supalite (supalite-sqlite-postgres) vs Supabase-local — Data + Auth + RLS + readback", () => {
  it("runs the same scenario on both real targets and every compared path agrees", async () => {
    const scenario = loadScenario("peer-data-auth-rls-smoke.json");
    const referenceKind = "supalite-sqlite-postgres" as const;
    const candidateKind = "supabase-local" as const;

    const handles: TargetHandle[] = [
      {
        slot: "reference",
        spec: supaliteSpec("reference"),
        driver: createSupaliteDriver(referenceKind, { scenarioResources: scenario.resources }),
      },
      {
        slot: "candidate",
        spec: supabaseLocalSpec("candidate"),
        driver: createSupabaseLocalDriver({ scenarioResources: scenario.resources }),
      },
    ];

    const result = await runScenario(scenario, handles);
    expect(
      result.state,
      JSON.stringify(
        [...result.targets].map(([s, t]) => [s, t.attempts.map((a) => `${a.stepId}:${a.status}`)]),
      ),
    ).toBe("complete");

    const reference = result.targets.get("reference")!;
    const candidate = result.targets.get("candidate")!;
    const scenarioDigest = computeScenarioDigest(scenario);

    const allResults = COMPARED_STEPS.flatMap((stepId) => {
      const refObs = reference.semanticObservations.get(`${stepId}:1`);
      const candObs = candidate.semanticObservations.get(`${stepId}:1`);
      expect(refObs, `reference semantic observation for ${stepId}`).toBeDefined();
      expect(candObs, `candidate semantic observation for ${stepId}`).toBeDefined();
      return compareStep({
        scenarioId: scenario.id,
        scenarioDigest,
        scenarioRevision: scenario.revision,
        stepId,
        referenceSlot: "reference",
        candidateSlot: "candidate",
        referenceTarget: { kind: referenceKind, version: "0.9.0" },
        candidateTarget: {
          kind: candidateKind,
          version: candidate.identity!.implementationVersion,
        },
        referenceObservation: refObs!,
        candidateObservation: candObs!,
        referenceRawDigest: sha256OfCanonicalJson(
          reference.rawObservations.get(`${stepId}:1`) as never,
        ),
        candidateRawDigest: sha256OfCanonicalJson(
          candidate.rawObservations.get(`${stepId}:1`) as never,
        ),
        policy: L7_POLICY,
        registry: [],
        now: new Date(),
      });
    });

    const bad = allResults.filter(
      (r) => r.outcome === "new-divergence" || r.outcome === "inconclusive",
    );
    expect(
      bad,
      JSON.stringify(
        bad.map((r) => ({
          step: r.stepId,
          path: r.observablePath,
          outcome: r.outcome,
          exp: r.explanation.summary,
        })),
        null,
        2,
      ),
    ).toEqual([]);
    expect(allResults.length).toBeGreaterThan(0);
    expect(
      allResults.every((r) => r.outcome === "match-exact" || r.outcome === "match-semantic"),
    ).toBe(true);

    // Direct RLS evidence, independent of the comparator.
    const rowsOf = (t: typeof reference, step: string) =>
      (t.rawObservations.get(`${step}:1`)!.transport.responseBody as { rows: unknown[] }).rows;
    expect(rowsOf(reference, "step.select-owner")).toHaveLength(1);
    expect(rowsOf(candidate, "step.select-owner")).toHaveLength(1);
    expect(rowsOf(reference, "step.select-anon")).toHaveLength(0);
    expect(rowsOf(candidate, "step.select-anon")).toHaveLength(0);
  }, 300_000);
});

describe("L7 supabase-local failure-mode handling", () => {
  it("port allocation: two scaffolded projects get distinct ids and distinct leased API ports", async () => {
    const a = await scaffoldSupabaseLocalProject(
      path.join(REPO_ROOT, "node_modules", ".cache", `sd-l7-a-${Date.now()}`),
      LOCAL_CONFIG,
    );
    const b = await scaffoldSupabaseLocalProject(
      path.join(REPO_ROOT, "node_modules", ".cache", `sd-l7-b-${Date.now()}`),
      LOCAL_CONFIG,
    );
    projects.push(a.projectId, b.projectId);
    expect(a.projectId).not.toBe(b.projectId);
    expect(a.apiPort).not.toBe(b.apiPort);
    expect(a.dbPort).not.toBe(b.dbPort);
  }, 120_000);

  it("cleanup/recovery: forceCleanupProject is idempotent and safe on an unknown project id", async () => {
    await expect(forceCleanupProject("sdsblocalffffffffffff")).resolves.toBeUndefined();
    await expect(forceCleanupProject("sdsblocalffffffffffff")).resolves.toBeUndefined();
  }, 30_000);

  it("identity mismatch: a wrong requested CLI version finalizes the run inconclusive, never a silent result", async () => {
    const scenario = loadScenario("peer-data-auth-rls-smoke.json");
    const driver = createSupabaseLocalDriver({ scenarioResources: scenario.resources });
    // A valid but wrong requested version: the driver still installs the real pinned CLI,
    // the engine sees requested "9.9.9" != observed "2.116.0" and refuses to freeze a plan.
    const spec = supabaseLocalSpec("mismatch", { package: { name: "supabase", version: "9.9.9" } });
    const result = await runScenario(scenario, [{ slot: "mismatch", spec, driver }]);
    expect(result.state).toBe("inconclusive");
    expect(result.plan, "no ExecutionPlan is frozen on an identity mismatch").toBeUndefined();

    // The stack that provisioning brought up for `identify()` must still be torn down —
    // an abnormal failure caught at plan-freeze reaches `session.teardown()` via the FSM's
    // recovery path, it is never silently skipped (§4.2/§4.6). This test file runs alone,
    // so no `sdsblocal*` container should remain.
    const leftover = spawnManaged(
      "bash",
      ["-c", `docker ps -aq --filter "name=sdsblocal" | wc -l`],
      {
        cwd: process.cwd(),
        env: process.env,
      },
    );
    await leftover.waitForExit();
    expect(leftover.stdout().trim(), "supabase-local stack leaked after identity mismatch").toBe(
      "0",
    );
  }, 180_000);

  it("target death: killing the container stack mid-run makes the engine finalize inconclusive (target-lost), not a false pass", async () => {
    const project = await scaffoldSupabaseLocalProject(
      path.join(REPO_ROOT, "node_modules", ".cache", `sd-l7-death-${Date.now()}`),
      LOCAL_CONFIG,
    );
    projects.push(project.projectId);
    await startStack(project);
    const session = new SupabaseLocalTargetSession(
      "sd-death" as never,
      project,
      { put: () => "sec-x" as never, reveal: () => "", fingerprint: () => "", has: () => false },
      new Map(),
      // This target-death probe only needs a working client; the package's own pinned
      // 2.97.0 is fine here (the client-contract path is exercised via the driver elsewhere).
      { createClient, version: "2.97.0" },
    );

    // Stack is alive: the target answers (an ordinary application error, not a harness failure).
    const before = await session.execute(
      {
        stepId: "s1" as never,
        attempt: 1,
        operation: { id: "data.select", version: "1" },
        input: { table: "nope" },
      },
      new AbortController().signal,
    );
    expect(before.category).not.toBe("harness-failure");

    // Kill the containers out from under the driver.
    const kill = spawnManaged(
      "bash",
      [
        "-c",
        `docker ps -q --filter "name=supabase_.*_${project.projectId}" | xargs -r docker kill`,
      ],
      { cwd: process.cwd(), env: process.env },
    );
    await kill.waitForExit();

    const after = await session.execute(
      {
        stepId: "s2" as never,
        attempt: 1,
        operation: { id: "data.select", version: "1" },
        input: { table: "nope" },
      },
      new AbortController().signal,
    );
    expect(after.category).toBe("harness-failure");
    expect(after.harnessFailureReason).toBe("target-lost");

    await session.teardown("failure", new AbortController().signal);
  }, 240_000);
});
